//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duck_2_Spark__Attiny_85_.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duck_2_Spark__Attiny_85_.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //should code be runned in this loop?
        ///	if (i != 0) {
        ///		DigiKeyboard.sendKeyStroke(0);
        ///
        ///		//parse raw duckencoder script
        ///		for (int i=0; i&lt;DUCK_LEN; i+=2)
        ///		{
        ///			uint8_t key = pgm_read_word_near(duckraw + i);
        ///			uint8_t mod = pgm_read_word_near(duckraw + i+1);
        ///			if (key == 0) //delay (a delay&gt;255 is split into a sequence of delays)
        ///			{
        ///				DigiKeyboard.delay(mod);
        ///			}
        ///			else DigiKeyboard.sendKeyStroke(key,mod);
        ///		}
        ///		i--;
        ///		DigiKeyboard.delay(%d); //wait %d milliseconds before next loop iteration
        ///
        ///	}
        ///	el [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string body {
            get {
                return ResourceManager.GetString("body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///* Sketch generated by duck2spark from Marcus Mengs aka MaMe82
        ///* C# Edition by NHTHEBEST
        ///*/
        ///#include &quot;&quot;DigiKeyboard.h&quot;&quot;.
        /// </summary>
        internal static string head {
            get {
                return ResourceManager.GetString("head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HelpStr {
            get {
                return ResourceManager.GetString("HelpStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to void setup()
        ///{
        ///	// initialize the digital pin as an output.
        ///	pinMode(0, OUTPUT); //LED on Model B
        ///	pinMode(1, OUTPUT); //LED on Model A
        ///	DigiKeyboard.delay(2500); //wait 2500 milliseconds before first run, to give target time to initialize
        ///}
        ///
        ///void loop()
        ///{.
        /// </summary>
        internal static string init {
            get {
                return ResourceManager.GetString("init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] keyboard {
            get {
                object obj = ResourceManager.GetObject("keyboard", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
